site_name: CFD Portfolio - Ajay

theme:
  name: material

nav:
  - Home: index.md
  - Project 1:
      - Overview: project-1/overview.md
      - Governing Equations: project-1/governing-equations.md
      - Numerical Method: project-1/numerical-method.md
      - Implementation: project-1/implementation.md
      - Tools & Stack: project-1/tools.md
      - Challenges & Debugging: project-1/challenges.md
      - Results: project-1/results.md
      - Learnings: project-1/learnings.md
      - Future Work: project-1/future_work.md

markdown_extensions:
  - pymdownx.superfences

plugins:
  - search
  - mermaid2
  
