site_name: CFD Portfolio - Ajay

theme:
  name: material

nav:
  - Home: index.md
  - Project 1:
      - Overview: project-1-Species_transport_solver/overview.md
      - Governing Equations: project-1-Species_transport_solver/governing-equations.md
      - Numerical Method: project-1-Species_transport_solver/numerical-method.md
      - Implementation: project-1-Species_transport_solver/implementation.md
      - Tools & Stack: project-1-Species_transport_solver/tools.md
      - Challenges & Debugging: project-1-Species_transport_solver/challenges.md
      - Results: project-1-Species_transport_solver/results.md
      - Learnings: project-1-Species_transport_solver/learnings.md
      - Future Work: project-1-Species_transport_solver/future_work.md
  - Project 2:
      - Summary: project-2-Species_transport_temperature_and_buouancy_solver/summary.md
      - Overview: project-2-Species_transport_temperature_and_buouancy_solver/overview.md
      - Vector Calculus: project-2-Species_transport_temperature_and_buouancy_solver/vector-calculus-basics.md
      - Governing Equations: project-2-Species_transport_temperature_and_buouancy_solver/governing-equations.md
      - Numerical Method: project-2-Species_transport_temperature_and_buouancy_solver/numerical-method.md
      - Implementation: project-2-Species_transport_temperature_and_buouancy_solver/implementation.md
      - Tools & Stack: project-2-Species_transport_temperature_and_buouancy_solver/tools.md
      - Challenges & Debugging: project-2-Species_transport_temperature_and_buouancy_solver/challenges.md
      - Results: project-2-Species_transport_temperature_and_buouancy_solver/results.md
      - Learnings: project-2-Species_transport_temperature_and_buouancy_solver/learnings.md
      - Future Work: project-2-Species_transport_temperature_and_buouancy_solver/future_work.md
  - Project 3:
      - Summary: project-3-vortex_dynamics/summary.md
      - Overview: project-3-vortex_dynamics/overview.md
      - Governing Equations: project-3-vortex_dynamics/governing-equations.md
      - Numerical Method: project-3-vortex_dynamics/numerical-method.md
      - Implementation: project-3-vortex_dynamics/implementation.md
      - LIbraries used: project-3-vortex_dynamics/libraries_used.md
      - Challenges & Debugging: project-3-vortex_dynamics/challenges.md
      - Results: project-3-vortex_dynamics/results.md
      - Learnings: project-3-vortex_dynamics/learning.md
      - Future Work: project-3-vortex_dynamics/future-work.md
  - Project- Ahmed Body:
      - Overview: project-Ahmed-body/overview.md
      - Governing Equations: project-Ahmed-body/governing-equations.md
      - Numerical Method: project-Ahmed-body/numerical-method.md
      - Implementation: project-Ahmed-body/implementation.md
      - Tools & Stack: project-Ahmed-body/tools.md
      - Challenges & Debugging: project-Ahmed-body/challenges.md
      - Results: project-Ahmed-body/results.md
      - Learnings: project-Ahmed-body/learnings.md
      - Future Work: project-Ahmed-body/future_work.md
  - Project- ROM for Lid Driven Cavity:
      - Overview: project-4-ROM_lid_driven_cavity/overview.md
      - Governing Equations: project-4-ROM_lid_driven_cavity/governing-equations.md
      - ROM Implementation: project-4-ROM_lid_driven_cavity/ROM-implementation.md
      - Simualtion Logic: project-4-ROM_lid_driven_cavity/simulation-logic.md
      - Tools & Stack: project-4-ROM_lid_driven_cavity/tools.md
      - Challenges & Debugging: project-4-ROM_lid_driven_cavity/challenges.md
      - Results: project-4-ROM_lid_driven_cavity/results.md
      - Learnings: project-4-ROM_lid_driven_cavity/learnings.md
      - Future Work: project-4-ROM_lid_driven_cavity/future_work.md

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: false


plugins:
  - search
  - mermaid2

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
