site_name: CFD Portfolio - Ajay

theme:
  name: material

nav:
  - Home: index.md
  - Project 1:
      - Overview: project-1-Species_transport_solver/overview.md
      - Governing Equations: project-1-Species_transport_solver/governing-equations.md
      - Numerical Method: project-1-Species_transport_solver/numerical-method.md
      - Implementation: project-1-Species_transport_solver/implementation.md
      - Tools & Stack: project-1-Species_transport_solver/tools.md
      - Challenges & Debugging: project-1-Species_transport_solver/challenges.md
      - Results: project-1-Species_transport_solver/results.md
      - Learnings: project-1-Species_transport_solver/learnings.md
      - Future Work: project-1-Species_transport_solver/future_work.md
  - Project 2:
      - Overview: project-2-Ahmed_Body/ahmed-body.md

markdown_extensions:
  - pymdownx.superfences

plugins:
  - search
  - mermaid2
  
